# only for github testing

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: [library_network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library"]
      interval: 3s
      timeout: 3s
      retries: 20
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/library
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "pip install --no-cache-dir -r /app/requirements.txt &&
            uvicorn main:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [library_network]
networks:
  library_network:
