services:
  db:
    image: postgres:15
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes: []
    networks:
      - library_network
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./app:/app
    command: >
      sh -c "pip install --no-cache-dir -r /app/requirements.txt &&
            uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/library
      PYTHONPATH: /app
    depends_on:
      - db
    networks:
      - library_network

networks:
  library_network:


# run with:
# docker compose up