name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests via Docker Compose
        run: |
          docker compose -f docker-compose-test.yml up --abort-on-container-exit --exit-code-from api

      - name: Show logs on failure
        if: failure()
        run: docker compose -f docker-compose-test.yml logs --no-color

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose-test.yml down -v
